[package]
name = "feeds"
version = "0.1.0"
authors = ["richard <richard@radagast.nu>"]

[dependencies]
chrono = { version = "0.4.3", features = ["serde"] }
diesel = { version = "1.2.2", features = ["postgres", "chrono"] }
dotenv = "0.11.0"
error-chain = ""
futures = "0.1"
hyper = "0.12"
log = "0.4.0"
num_cpus = ""
pretty_env_logger = ""
regex = "1.0.0"
rss = "1.5.0"
serde = ""
serde_derive = ""
serde_json = ""
tokio = "0.1"
tokio-fs = ""
tokio-io = ""
url = ""
